build: update Maven workflow
- Add step to checkout code before setting up JDK
- Update publish test report step to use action-junit-report
- Ensure test report is published regardless of previous step's status

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -20,6 +20,7 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Checkout Code
       - uses: actions/checkout@v4
       - name: Set up JDK 22
         uses: actions/setup-java@v4
@@ -27,22 +28,22 @@ jobs:
           java-version: '22'
           distribution: 'temurin'
           cache: maven
+
       - name: Run the Maven verify phase
         run: mvn --batch-mode --update-snapshots verify
+
       - name: Build
         run: mvn --batch-mode -DskipTests package
 
       - name: Test
         run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
 
-      - name: Report
-        uses: dorny/test-reporter@v1
-        if: always()
-        with:
-          name: Maven Tests
-          path: target/surefire-reports/*.xml
-          reporter: java-junit
-          fail-on-error: true
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: |
+          success() || failure() # always run even if the previous step fails
+          with:
+            report_paths: '**/target/surefire-reports/TEST-*.xml'
 
       # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
       - name: Submit Dependency Snapshot
